---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: pretty-format-json
        args: [--autofix, --indent=4]
      - id: trailing-whitespace
  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.12.0
    hooks:
      - id: markdownlint
        args: [--config, .mdlrc]
  - repo: local
    hooks:
    -   id: sort-docker-compose
        name: Sort Docker Compose files
        entry: python sort-docker-compose.py
        language: system
        types: [yaml]
        files: docker-compose.(yaml|yml)$
