---
include:
  - path: ./duplicati/docker-compose.yaml
  - path: ./portainer/docker-compose.yaml
  - path: ./pi-hole/docker-compose.yaml
  - path: ./home-assistant/docker-compose.yaml
  - path: ./plex/docker-compose.yaml
networks:
  home-server:
    name: home-server
    driver: bridge
