---
version: '3'
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:2025.04.0
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 8080:80/tcp
    env_file:
      - .env
    environment:
      - TZ=US/Central
    volumes:
      - pihole:/etc/pihole
      - dnsmasq:/etc/dnsmasq.d
    networks:
      - macvlan
    restart: unless-stopped
volumes:
  dnsmasq:
    name: pi-hole_dnsmasq
  pihole:
    name: pi-hole_pihole
networks:
  macvlan:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - gateway: 192.168.1.1
          ip_range: 192.168.1.20/32
          subnet: 192.168.1.0/24
    name: pihole
