---
version: '3.8'
services:
  plex:
    container_name: plex
    image: lscr.io/linuxserver/plex:1.41.6
    environment:
      - PUID=1029
      - PGID=65537
      - TZ=US/Central
      - UMASK=022
      - VERSION=docker
    volumes:
      - /volume1/docker/plex:/config
      - /volume1/plex/movies:/movies
      - /volume1/plex/tv:/tv
    network_mode: host
    restart: unless-stopped
    pull_policy: missing
    security_opt:
      - no-new-privileges:true
