---
services:
  duplicati:
    container_name: duplicati
    image: lscr.io/linuxserver/duplicati:2.0.7
    ports:
      - 8200:8200
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=US/Central
    volumes:
      - config:/config
      - backups:/backups
      - source:/source
      - home-assistant_config:/source/volume1
      - portainer_data:/source/volume2
      - pi-hole_pihole:/source/volume3
      - pi-hole_dnsmasq:/source/volume4
    networks:
      - duplicati
    restart: unless-stopped
    pull_policy: missing
volumes:
  backups:
    name: duplicati_backups
  config:
    name: duplicati_config
  home-assistant_config:
    external: true
  pi-hole_dnsmasq:
    external: true
  pi-hole_pihole:
    external: true
  portainer_data:
    external: true
  source:
    name: duplicati_source
networks:
  duplicati:
    name: duplicati
