---
version: "3.8"
services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:2.0.7
    pull_policy: missing
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=US/Central
    volumes:
      - config:/config
      - backups:/backups
      - source:/source
      - home-assistant_home-assistant:/source/volume1
      - portainer_portainer:/source/volume2
    ports:
      - 8200:8200
    restart: unless-stopped
volumes:
  config:
  backups:
  source:
  home-assistant_home-assistant:
    external: true
  portainer_portainer:
    external: true
