---
version: '3.8'
services:
  homeassistant:
    container_name: homeassistant
    image: lscr.io/linuxserver/homeassistant:2023.11.1
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=US/Central
    volumes:
      - config:/config
    network_mode: host
    restart: unless-stopped
    pull_policy: missing
volumes:
  config:
    name: home-assistant_config
