---
version: "2.1"
services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant:2023.6.3
    container_name: homeassistant
    #Host vs. Bridge
    # Home Assistant can discover and automatically configure zeroconf/mDNS and UPnP
    # devices on network. Must use network_mode: host for this functionality.
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config:/config
    # ports:
      # - 8123:8123 #optional. Use if not running in network_mode: host
    restart: unless-stopped
