---
services:
  jellyfin:
    container_name: jellyfin
    image: lscr.io/linuxserver/jellyfin:10.9.11
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1901:1900/udp
    environment:
      - PUID=1029
      - PGID=65537
      - TZ=US/Central
      - UMASK=022
    volumes:
      - config:/config
      - /volume1/plex/movies:/movies:ro
      - /volume1/plex/tv:/tv:ro
    restart: unless-stopped
    pull_policy: missing
    security_opt:
      - no-new-privileges:true
volumes:
  config:
    name: jellyfin_config
