---
services:
  portainer:
    container_name: portainer-ce
    image: portainer/portainer-ce:2.19.1
    ports:
      - 8000:8000
      - 9000:9000
      - 9443:9443
    environment:
      - name=value
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
    networks:
      - portainer
    restart: unless-stopped
    pull_policy: missing
volumes:
  data:
    name: portainer_data
networks:
  portainer:
    name: portainer
