---
version: "3.8"
services:
  portainer:
    image: portainer/portainer-ce:2.19.1
    pull_policy: missing
    container_name: portainer-ce
    environment:
      - name=value
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
    restart: unless-stopped
    ports:
      - 8000:8000
      - 9000:9000
      - 9443:9443
volumes:
  portainer:
